[package]
name = "day-04"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }

[dev-dependencies]

# [[bench]]
# name = "day-04-bench"
# path = "benches/benchmarks.rs"
# harness = false
